### ISSUE TITLE
Support for blob:

### ISSUE THREAD

**Issue by grafikkaos** [BePsvPT/secure-headers#10]
Hi,

Is there support for blob: with this package? I am currently using it and I am getting the following error:

Refused to load media from 'blob:https://xxxxxxxx.ngrok.io/31d4ff8f-d69e-48ec-b504-ac8c3cab5909' because it violates the following Content Security Policy directive: "media-src http://*.ngrok.io data:".

Is there way I can have this fixed?

Thanks

**Comment by BePsvPT** [comment]
Hi @grafikkaos, sorry for late replying.

Currently, you can use `types` directive, like

```php
'media-src' => [
  'types' => [
    'blob:',
  ],
],
```

Hope this will help you.

**Comment by grafikkaos** [comment]
Ah thank you... Will give that a try and see if that helps :)

**Comment by grafikkaos** [comment]
It works :)  Thank you !! 👍

**Comment by clickblipclick** [comment]
Is there a way to support loading styles as a blob:?

If you try to add `blob:` as an allowed `style-src` I get the following error:
The source list for Content Security Policy directive 'style-src' contains an invalid source: 'http://blob:'. It will be ignored.

**Comment by BePsvPT** [comment]
@clickblipclick 

use `types` directive, see above comment
