### ISSUE TITLE
Laravel Issue

### ISSUE THREAD

**Issue by chriskivaze** [BePsvPT/secure-headers#14]
When i add the global  middleware `\Bepsvpt\SecureHeaders\SecureHeadersMiddleware::class,` in my `app/http/kernel.php `, whenever a validation fails in a form it redirects back to '/' route instead of back to the form with errors. or whenever i call `redirect()->back()` method it redirects to the default route '/' . 
This only happens with the global middleware set.

**Comment by ctf0** [comment]
@chriskivaze check https://www.sentinelstand.com/article/laravel-redirects-break-when-using-origin-referrer-policy

**Comment by chriskivaze** [comment]
@ctf0 thanks that helped

**Comment by christattum** [comment]
Just encountered this same issue. Thanks!
