### ISSUE TITLE
Tags after merge

### ISSUE THREAD

**Issue by ruudy-es** [BePsvPT/secure-headers#19]
Hi,

Can you please tag this and https://github.com/BePsvPT/csp-builder after my PRs merge?

Also increase the composer.json line that refers to csp-builder.

I do not why but it looks like default-src is not adding the values on "allow" position to the 'self' value, will try to give you more info after solve the prefecth problem we are having.

Thanks!

**Comment by BePsvPT** [comment]
Hi @ruudy-es,

Thanks for helping me to improve the package. 👍 

After merging your pull request and completing the rest part, I just releasing a new version that support CSP level 3. If you still encounter the same problem, just reply in this issue to let me know it.
