### ISSUE TITLE
Error when loading data:image - violates csp

### ISSUE THREAD

**Issue by redroses** [BePsvPT/secure-headers#20]
Getting error loading data:image.

FileList {0: File(805286), length: 1}
edit:1 Refused to load the image 'data:image/jpeg;base64,/9j/4T+DRXhpZk=' because it violates the following Content Security Policy directive: "img-src 'self' http://ajax.googleapis.com http://cdnjs.cloudflare.com http://*.tawk.to http://code.jquery.com".

` 'img-src' => [
				'allow' => [
					 $protocol . 'ajax.googleapis.com',
					 $protocol . 'cdnjs.cloudflare.com',
					 $protocol . '*.tawk.to',
					 $protocol . 'code.jquery.com',
				],
				'self' => true,
				'data' => true,
		  ],
`
What am i doing wrong?
Thanks

**Comment by BePsvPT** [comment]
Hi @redroses,

In latest version, you should use `schemes` instead of `data`.

```php
'img-src' => [
  'schemes' => [
    'data:',
  ],
],
```

**Comment by redroses** [comment]
Awesome. Worked perfectly. Thanks for the quick reply.
