### ISSUE TITLE
Please provide better examples for csp

### ISSUE THREAD

**Issue by dsingleton47** [BePsvPT/secure-headers#21]
Please provide better examples for CSP in the documentation, if I provide anything other than:
'self' => true I the result is an empty img-src value, this is true if I provide an array as well. for example using the example from paragonie/csp-builder with:

'self' => true,
'data' => true

my resulting policy only has self, data doesn't work at all. If I try to provide a domain, the same is true.

**Comment by JohanMa4** [comment]
Hi @BePsvPT, how are you man?, i have troubles by adding the data attribute on:
`'font-src' => ['data' => true]`
`img-src' => ['data' => true]`

The 'data' attribute not works!

Can you help me?

Thanks!

**Comment by BePsvPT** [comment]
Hi @dsingleton47 and @JohanMa4,

I have updated the [document](https://github.com/BePsvPT/secure-headers/tree/master/docs). If you have any suggestion, I will deeply appreciate your feedback.

**Comment by agenciatamandua** [comment]
Please improve Documents, the CSP part is very bad at understanding.
Could you give better examples of how to use CSP?

**Comment by bepsvpt** [comment]
Hi @agenciatamandua,

If you can provide your requirements, I can include it in examples.
