### ISSUE TITLE
How to setup 'script-src' on https protocol?

### ISSUE THREAD

**Issue by JohanMa4** [BePsvPT/secure-headers#24]
Hi, i've been trying to setup the 'script-src' on 'secure-headers.php' file, but i don't have some response setting up this options.

Can you help me with any information?

Thanks.

**Comment by BePsvPT** [comment]
Hi @JohanMa4,

If you want to allow `https` protocol on `script-src` directive, just add `https` to `schemes`.

```php
'script-src' => [
  'schemes' => [
    'https:',
  ],
]
```
