### ISSUE TITLE
How to generate "nonce" and add generated code to script and style tags?

### ISSUE THREAD

**Issue by JohanMa4** [BePsvPT/secure-headers#25]
Hi @BePsvPT, i have another trouble, how can i add a "nonce" key and add it to script an style tags?
I want to fix Content Security Policy on my Laravel App.

**Comment by BePsvPT** [comment]
Hi @JohanMa4,

After setting `add-generated-nonce` to `true` in `script-src` and `style-src` directives, you can use `SecureHeaders::nonce()` to get nonce value and add to `script` or `style` tags.

**Comment by Zabanya** [comment]
@BePsvPT could you update doc to add `'SecureHeaders' => Bepsvpt\SecureHeaders\SecureHeaders::class` in the for it to work on blade template

**Comment by BePsvPT** [comment]
Hi @Zabanya,

Can you give an example that using it in blade template?

**Comment by Zabanya** [comment]
add aliases in config/app/php
```
'SecureHeaders' => Bepsvpt\SecureHeaders\SecureHeaders::class
```

blade usage
```
<script nonce="{{ SecureHeaders::nonce() }}"> ...
```

**Comment by BePsvPT** [comment]
Hi @Zabanya,

I have updated the document, you can find it [here](https://github.com/BePsvPT/secure-headers/tree/master/docs#content-security-policy).
