### ISSUE TITLE
Add New Header: Feature Policy

### ISSUE THREAD

**Issue by austintoddj** [BePsvPT/secure-headers#27]
Love the package, great work on it.

Could you look into adding support for the new security header: `Feature Policy`?

Details on what it entails can be found [here](https://scotthelme.co.uk/a-new-security-header-feature-policy/).

**Comment by JohanMa4** [comment]
Hi @austintoddj, @BePsvPT will implement it this weekend, you can check my question on this [post](https://github.com/BePsvPT/secure-headers/issues/26).

I hope this help you

**Comment by BePsvPT** [comment]
Hi @austintoddj and @JohanMa4,

You can test `feature-policy` header in latest commit, if you have any question, please leave a comment and I will reply soon.

**Comment by JohanMa4** [comment]
Thanks @BePsvPT i wIll check it, i hope let you a good feedback.

**Comment by austintoddj** [comment]
Thank you @BePsvPT!
