### ISSUE TITLE
Error EvalError: for scipt

### ISSUE THREAD

**Issue by hasiashiana** [BePsvPT/secure-headers#31]
Hi

Im getting the below error in the console with the upgrade

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'

This is my script-src block in config/secure-headers.php

Can some one please let me know what should I change ?

'script-src' => [
            'allow' => [
                'https://cdn.jsdelivr.net', // signature pad
            ],

            'hashes' => [
                // ['sha256' => 'hash-value'],
            ],

            'nonces' => [
                //
            ],

            'schemes' => [
                // 'https:',
            ],

            'self' => true,

            'unsafe-inline' => true,

            'unsafe-eval' => false,
        ]

**Comment by BePsvPT** [comment]
Hi @hasiashiana,

When setting `unsafe-eval` to `false`. `eval()` and `Function()` will not enable to use in your code or third party library. You can find more information from MDN: [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_eval_expressions](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_eval_expressions).

If you are not using these function in your code, it may be third party libraries using it. You can check whether it provides CSP-compliant version or not.

**Comment by hasiashiana** [comment]
@BePsvPT  Thanks a lot. This clears my doubt.
