### ISSUE TITLE
Working with default settings.

### ISSUE THREAD

**Issue by voske** [BePsvPT/secure-headers#34]
Hey guys,

I have a isue with the secure hearders. I installed it true composer, no problems there. But now it's so secure, i can't even see my bootstrap layout. Should it work on default or i'am missing something? Thanks in advance.

**Comment by BePsvPT** [comment]
I think this is caused by CSP header. You can config it [at here](https://github.com/BePsvPT/secure-headers/blob/5.3.3/config/secure-headers.php#L373-L520).

**Comment by BePsvPT** [comment]
Closed due to inactivity, feel free to open a new issue if you have any question.
