### ISSUE TITLE
Get  Error parsing header in Chrome Console 

### ISSUE THREAD

**Issue by Kokil** [BePsvPT/secure-headers#36]
`Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 13. The default protections will be applied.`

**Comment by BePsvPT** [comment]
Hi @Kokil,

What value did you set for `X-XSS-Protection`?

**Comment by Kokil** [comment]
Hi @BePsvPT,
Here is the value X-XSS-Protection 
'x-xss-protection' => '1; mode=block',

**Comment by BePsvPT** [comment]
https://github.com/symfony/symfony/issues/30134

I found this issue is same error message as you provide. Did you send `X-XSS-Protection` header in other place? Like Nginx or Apache.

**Comment by Kokil** [comment]
No, I haven't

**Comment by BePsvPT** [comment]
Could you use browser developer tools to see the value of `X-XSS-Protection`?

**Comment by Kokil** [comment]
Yes, you are right. I got double X-XSS-Protection.

**Comment by BePsvPT** [comment]
If you have any further question, feel free to open a new issue.
