### ISSUE TITLE
Unrecognized feature: 'display-capture'

### ISSUE THREAD

**Issue by katranci** [BePsvPT/secure-headers#37]
Hey 👋 I'm getting the following error on Chrome. Is _display-capture_ a valid policy? 

```
Error with Feature-Policy header: Unrecognized feature: 'display-capture'.
```

**Comment by BePsvPT** [comment]
Hi @katranci,

Currently, `display-capture` is only supported in Firefox now.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy#Browser_compatibility

**Comment by katranci** [comment]
I see, thanks @BePsvPT 👍

**Comment by matheuscamarques** [comment]
how do use 'display-capture' in chrome ?

**Comment by eladalon1983** [comment]
1. MDN is wrong. `display-capture` is supported by Safari, too. I've filed an MDN bug, but they're not responsive.
2. The `display-capture` permissions policy has not previously been supported on Chrome, but I have implemented it and it's shipping in m93.
