### ISSUE TITLE
Image data: Question

### ISSUE THREAD

**Issue by HDVinnie** [BePsvPT/secure-headers#41]
Im getting a lot of the following. 

[![Screen-Shot-2019-10-30-at-3-17-43-PM.png](https://i.postimg.cc/cCS55zQb/Screen-Shot-2019-10-30-at-3-17-43-PM.png)](https://postimg.cc/62M08Ybr)

My Config is so:
```
        'img-src' => [
            'schemes' => [
                'data:',
                'https:',
            ],
            'self' => true,
            'data' => true,
        ],
```

How can I allow all these?

**Comment by BePsvPT** [comment]
Hi @HDVinnie,

Which version are you used and could you paste full csp config?

**Comment by HDVinnie** [comment]
@BePsvPT 

`"bepsvpt/secure-headers": "^5.3",` in composer.json

```
"name": "bepsvpt/secure-headers",
            "version": "5.5.0",
```
in composer lock

Full config:
https://pastebin.com/49Udqb3b

**Comment by HDVinnie** [comment]
@BePsvPT any ideas?

**Comment by BePsvPT** [comment]
I can't reproduce it. Can you paste the CSP header from browser response?

**Comment by HDVinnie** [comment]
It seemed to be a cache issue my end. Sorry about that.
