### ISSUE TITLE
Add Nonce on Javascript Navigation

### ISSUE THREAD

**Issue by PanjiNamjaElf** [bepsvpt/secure-headers#45]
Hello..
How to add nonce on javascript navigation without enable 'unsafe-inline' in 'script-src' ?

Ex:
<a href="javascript:void(0);" class="waves-effect">

I want add nonce on 'javascript:void(0);' or similar script like that
Thanks!

**Comment by bepsvpt** [comment]
Hi @PanjiNamjaElf,

Is [doc example](https://github.com/bepsvpt/secure-headers/blob/6.0.0/DOCS.md#content-security-policy) what you need?

Or you want something like `<a href="javascript:void(0)">link</a>`?

**Comment by PanjiNamjaElf** [comment]
Yes...
I want like this

```
     <a href="javascript:void(0);" class="waves-effect">
      <i class="ti-money"></i>
      <span>@lang('menu')<span class="menu-arrow"></span>
     </a>
```

I try put nonce like this `<a href="javascript:void(0);" class="waves-effect" nonce="ABC==">`
But not work...
When i enable `unsafe-inline` and has some nonce in my inline script unsafe-inline will be ignored

**Comment by bepsvpt** [comment]
Is it using `<span>...</span>` instead of `<a>...</a>` possible?

**Comment by PanjiNamjaElf** [comment]
Is not work..
But i have resolved it...

I enable `unsafe-hashes` and hashed `javascript:void(0)` to sha384 and put it on `hashes` config `sha384`

Thank you!!

**Comment by bepsvpt** [comment]
Thanks for this information. I will add to example!
