### ISSUE TITLE
After setup for laravel, Content-Security-Policy header is not generated

### ISSUE THREAD

**Issue by hyquoccuong** [bepsvpt/secure-headers#57]
I see csp is enabled in config file secure-headers.php 

```
/*
     * Content Security Policy
     *
     * Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
     */

    'csp' => [
        'enable' => true,
```

But in header of my site Content-Security-Policy header is not generated

Results from https://securityheaders.com

Missing Headers

Content Security Policy is an effective measure to protect your site from XSS attacks. By whitelisting sources of approved content, you can prevent the browser from loading malicious assets.

How do I enable this header?

**Comment by hyquoccuong** [comment]
I tried some config here but it is not generated

https://barryvanveen.nl/blog/35-how-to-configure-security-headers-for-laravel

**Comment by bepsvpt** [comment]
Did you add the middleware to `app/Http/Kernel.php`?

You can visit https://github.com/bepsvpt/secure-headers#laravel-project to check it.

**Comment by hyquoccuong** [comment]
yep I added this to kernel

**Comment by hyquoccuong** [comment]
```
  protected $middleware = [
        \Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
        \Bepsvpt\SecureHeaders\SecureHeadersMiddleware::class, //https://github.com/bepsvpt/secure-headers
    ];
```

**Comment by hyquoccuong** [comment]
After I update some options in config file secure-headers.php, now it enabled
```
        // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/base-uri
        'base-uri' => [
			'self' => true,
        ],
```
```
         // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
        'frame-ancestors' => [
			'self' => true,
        ],
```
```
        // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/object-src
        'object-src' => [
            'none' => true,
        ],
```

```
        // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
        'script-src' => [

            'none' => true,
        ]
```

**Comment by karamvirs** [comment]
Hi,
having a similar issue. 
I need to set the `frame-ancestors` directive to multiple URIs. But it seems only this seems to work.
`
'frame-ancestors' => [
			'self' => true,
        ],
`

I tried to add it like:
`
'frame-ancestors' => [
			'URI1' => true,
			'URI2' => true,
        ],
`
doesnt work.
Also tried some other ways.

**Comment by jalmatari** [comment]
> Hi, having a similar issue. I need to set the `frame-ancestors` directive to multiple URIs. But it seems only this seems to work. `'frame-ancestors' => [ 'self' => true, ],`
> 
> I tried to add it like: `'frame-ancestors' => [ 'URI1' => true, 'URI2' => true, ],` doesnt work. Also tried some other ways.
> 
> Do you know a solution to add multiple URIs other than just specifying self?
```
    'frame-ancestors' => [
            'allow' => [
                env('CUSTOM_CORS_DOMAIN'),
                //...
            ],
        ],
```
