### ISSUE TITLE
X-Powered-By keep showing when I leave it empty in config file

### ISSUE THREAD

**Issue by hyquoccuong** [bepsvpt/secure-headers#58]
In Laravel config/secure-headers.php
```
    /*
     * X-Powered-By
     *
     * Note: it will not add to response header if the value is empty string.
     */
    'x-powered-by' => '',
```
But in header it shows 

X-Powered-By: PHP/7.2.28
-----------------------------------------------------------------
If I change the value:
```
'x-powered-by'  => config('app.name'),
```
Header shows:

X-Powered-By: PHP/7.2.28
X-Powered-By: Laraspace
--------------------------------------------------------------------
And if I change the config to

    'x-powered-by' => [
        'enable' => false,
    ],

Now it shows: 

X-Powered-By: PHP/7.2.28
X-Powered-By
----------------------------------------------------------------------
I just want to hide/remove it completely or just show one line with set value in config file, could you please let me know how to do that?

**Comment by tobias-trozowski** [comment]
not sure about your setup and i'm not a lara user but u might check https://www.php.net/manual/en/ini.core.php#ini.expose-php

**Comment by aesyondu** [comment]
I have the same issue. Have you found a workaround @hyquoccuong ?

```json
{
  "bepsvpt/secure-headers": "v6.3.0",
  "laravel/lumen-framework": "v5.8.13",
}
```

**Comment by aesyondu** [comment]
Nvm, thanks @tobias-trozowski. In my case it was the `php.ini`

1. verify that `expose_php` is **On**
```sh
php -i | grep expose
# expose_php => On => On
```

2. set `expose_php` to **Off** in `php.ini`
```
expose_php => Off => Off
```

3. restart server and verify header is not shown

**Comment by bepsvpt** [comment]
Close due to inactive.
