### ISSUE TITLE
Support SharedArrayBuffer updates in Chrome around May 2021

### ISSUE THREAD

**Issue by yosifeldman** [bepsvpt/secure-headers#60]
Got a warning in Chrome:
"[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M91, around May 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details."

Not found in the package any mentions of the headers that they are talking about:

Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin

**Comment by bepsvpt** [comment]
Hi @yosifeldman,

The `Cross-Origin-*-Policy` headers will be supported in the next release.
