### ISSUE TITLE
undefined index: x-content-type-options

### ISSUE THREAD

**Issue by ChaerilM** [bepsvpt/secure-headers#61]
![undef](https://user-images.githubusercontent.com/1352081/116028751-0c76be80-a682-11eb-8826-4e3aca864a24.png)

what did i do wrong?, pretty much clean install and enable config are set as env == production.

**Comment by bepsvpt** [comment]
Did you accidentally delete the `x-content-type-options` configuration?

https://github.com/bepsvpt/secure-headers/blob/7.1.0/config/secure-headers.php#L15-L23

**Comment by ChaerilM** [comment]
![xc](https://user-images.githubusercontent.com/1352081/116337155-e416cd80-a803-11eb-842a-96d19b779c24.png)

it's there, on both local and deployment, it only happens in the deployment which is annoying
