### ISSUE TITLE
Add CSP Report To 

### ISSUE THREAD

**Issue by NKazantsev** [bepsvpt/secure-headers#65]
Hi
Can you add CSP **Report To** option ?
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to

**Comment by repat** [comment]
https://github.com/bepsvpt/secure-headers/blob/master/config/secure-headers.php#L453

@NKazantsev this is now added

**Comment by bepsvpt** [comment]
Close due to inactive.
