### ISSUE TITLE
Add route whitelist

### ISSUE THREAD

**Issue by beard7** [bepsvpt/secure-headers#67]
Great package... in fact, too good.

I have an Outlook Addin that's served from my Laravel web app. It's a single page, but it requires users to be logged in, otherwise I'd host it outside of Laravel.

As soon as CSP is enabled, the Outlook Addin stops working and finding the cause is proving to be a nightmare.

Would it be possible to add a route whitelist so secure headers can be disabled for specific routes?

**Comment by bepsvpt** [comment]
You can reference [SecureHeadersMiddleware.php](https://github.com/bepsvpt/secure-headers/blob/7.2.0/src/SecureHeadersMiddleware.php) file to implement a customized middleware.

For example:
```php
$response = $next($request);

if (is whitelist route?) {
    return $response;
}

$headers = (new SecureHeaders(config('secure-headers', [])))->headers();

...
```
