### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by HDVinnie** [bepsvpt/secure-headers#68]

**Comment by dwightwatson** [comment]
Any reason you closed your PR?

Be great to see the support added now that Laravel 9.x has shipped.

**Comment by HDVinnie** [comment]
Been over a week with no response. I need to update some projects that rely on this so I plan to just maintain my own fork. I have reopened the PR on a new branch however.

**Comment by dwightwatson** [comment]
Cool, hopefully it'll grab the maintainer's attention this time around.

**Comment by barryvanveen** [comment]
I took the liberty to open another PR that also updates the tests and docs: #71
