### ISSUE TITLE
securityheaders.com still show Big red F 

### ISSUE THREAD

**Issue by arshadanjum167** [bepsvpt/secure-headers#76]
Hello All,

1.I have configured as per laravel project and security headers comes in first request of website but all other request like loading js and css that does not have configred security headers.

2.Also securityheaders.com still show Big red F for my website (https://workversatile.com)
Can anyone help me ?

**Comment by arshadanjum167** [comment]
Thanks @bepsvpt for quick response,
Yes this website show A but securityheaders.com does not show A .
@bepsvpt can you please tell me what is wrong with my all other js  and css files which does not security headers.

**Comment by bepsvpt** [comment]
Your server responds with 403 when using https://securityheaders.com to check your site. One of the possible reasons is your server blocks the requests come from https://securityheaders.com.

![image](https://user-images.githubusercontent.com/8221099/194055493-3e9ff242-a2bb-4614-98aa-1b97f942d31a.png)

**Comment by arshadanjum167** [comment]
okay what is perfect solution for this reason?

**Comment by bepsvpt** [comment]
I saw you are using cPanel, thus, I assume you host your website by a provider. I would suggest you contact your provider to ask them to help you solve this issue.

**Comment by bepsvpt** [comment]
Close due to inactive.
