### ISSUE TITLE
Eliminate Laravel dependency for non-Laravel users

### ISSUE THREAD

**Issue by compwright** [bepsvpt/secure-headers#77]
Kudos on a lightweight and well-organized package for handling all the security headers! This is just what I was looking for.

However this package has only one downside: installing it will install illuminate/support into my project, but I don't need that since I'm not running Laravel.

Could the following be moved to a separate package:

* src/SecureHeadersMiddleware.php
* src/SecureHeadersServiceProvider.php
* tests/SecureHeadersTest.php
* illuminate/support dependency
* Laravel-specific documentation

This change would make this package more attractive to non-Laravel users and lower maintenance since no dependencies means no dependencies to update down the road.

If that isn't an option or desirable, moving illuminate/support from `require` to `suggest` would help.

**Comment by bepsvpt** [comment]
Hi @compwright,

The `illuminate/support` dependency will be removed in the next release.

Separating into multiple packages is the best option for the issue you encountered. However, considering the maintenance cost, I may not be able to do this. Thus, I choose to solve this issue by removing the dependency.

**Comment by compwright** [comment]
Awesome, thanks @bepsvpt!
