### ISSUE TITLE
How can I apply the following in the "Content-Security-Policy" ?

### ISSUE THREAD

**Issue by Nemachtilli** [bepsvpt/secure-headers#84]
Can it work? "Content-Security-Policy" : "upgrade-insecure-requests"

**Comment by bepsvpt** [comment]
You can set upgrade-insecure-requests to true. You can find the relevant configuration at https://github.com/bepsvpt/secure-headers/blob/d08427a04739ea76014e2aeca81d6222a621ca7f/config/secure-headers.php#L490-L491

**Comment by Nemachtilli** [comment]
Ok thanks.

how do I write the permissions policy?

'ambient-light-sensor' => [
            'none' => false,

            '*' => false,

            'self' => true,

            'origins' => [https://domain.com],
        ],
        
        Is what I wrote correct?
        
        The following appears in the console to me:
        
        Error in console is = Error with Permissions-Policy header: Unrecognized feature: 'ambient-light-sensor'.

**Comment by bepsvpt** [comment]
Not all browsers support this directive. You can check the compatibility at [https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/ambient-light-sensor#browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/ambient-light-sensor#browser_compatibility).

**Comment by Nemachtilli** [comment]
Thank you very much for answering.

Can you ignore those warnings?

How safe is it to use upgrade-insecure-requests?

**Comment by bepsvpt** [comment]
> Can you ignore those warnings?

This is a browser warning; if the browser does not support this directive, it will simply be ignored.

> How safe is it to use upgrade-insecure-requests?

If your site is fully SSL (including the site itself, API requests, embedded images, and videos), it is safe to enable this directive.

**Comment by bepsvpt** [comment]
Closed due to inactivity. Please feel free to open a new issue if you have any further questions.
